//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderingSystem.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public string AddressName { get; set; }
        public string AddressPhone { get; set; }
        public string AddressDetail { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
